name: korbil_mobile
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  bloc: ^8.1.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0
  # google_fonts: ^5.1.0
  syncfusion_flutter_core: ^22.2.8
  syncfusion_flutter_datepicker: ^22.2.8
  flutter_slidable: ^3.0.0
  carousel_slider: ^4.2.1
  dotted_line: ^3.2.2
  dotted_border: ^2.0.0+3
  sliding_up_panel: ^2.0.0+1
  # flutter_calendar_week: ^2.0.0
  horizontal_week_calendar: ^0.0.11
  # flutter_neat_and_clean_calendar: ^0.3.11+25
  shared_preferences: ^2.2.0
  go_router: ^10.1.0
  get_it: ^7.6.0
  dio: ^5.3.2

dev_dependencies:
  bloc_test: ^9.1.2
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^5.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/imgs/ins/auth/
    - assets/imgs/ins/global/
    - assets/imgs/ins/global/i_menu/
    - assets/imgs/ins/global/s_menu/
    - assets/imgs/ins/lessons/
    - assets/imgs/ins/notifications/
    - assets/imgs/ins/profile/
    - assets/imgs/ins/school/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
          weight: 800
    - family: Lato
      fonts:
        - asset: assets/fonts/lato/Lato-Black.ttf
          weight: 800
        - asset: assets/fonts/lato/Lato-Bold.ttf
          weight: 500
        - asset: assets/fonts/lato/Lato-Regular.ttf
          weight: 400
