name: korbil_mobile
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  bloc:
  flutter:
    sdk: flutter
  flutter_bloc:
  flutter_localizations:
    sdk: flutter
  intl:
  # google_fonts: ^5.1.0
  syncfusion_flutter_core: 
  syncfusion_flutter_datepicker: ^25.1.39
  flutter_slidable: ^3.1.0
  carousel_slider:
  dotted_line:
  dotted_border: 
  sliding_up_panel: 
  # flutter_calendar_week: ^2.0.0
  horizontal_week_calendar:
  # flutter_neat_and_clean_calendar: ^0.3.11+25
  shared_preferences:
  go_router: 
  get_it:
  dio:
  file_picker:
  amplify_flutter:
  amplify_auth_cognito:
  equatable:

dev_dependencies:
  bloc_test:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  very_good_analysis: ^5.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/imgs/ins/auth/
    - assets/imgs/ins/global/
    - assets/imgs/ins/global/i_menu/
    - assets/imgs/ins/global/s_menu/
    - assets/imgs/ins/lessons/
    - assets/imgs/ins/notifications/
    - assets/imgs/ins/profile/
    - assets/imgs/ins/school/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
          weight: 800
    - family: Lato
      fonts:
        - asset: assets/fonts/lato/Lato-Black.ttf
          weight: 800
        - asset: assets/fonts/lato/Lato-Bold.ttf
          weight: 500
        - asset: assets/fonts/lato/Lato-Regular.ttf
          weight: 400
