name: Builds
on:
  push:
    branches:
      - main
  # pull_request:
  #   branches:
  #     - main

permissions:
  contents: write

jobs:
  draft-release:
    name: Build android
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false 
    steps:
      - uses: actions/checkout@v4
    
      # Set up Flutter.
      - name: Setup flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.5'
          channel: 'stable'
          cache: true
      - run: flutter doctor -v

      # Install Android dependency
      - name: Set up JDK 
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: zulu
          cache: gradle

      # - name: Delete pubspec.lock
      #   if: ${{ hashFiles('**/pubspec.lock') != '' }}
      #   run: rm **/pubspec.lock

      #   #clean cache
      # - name: Clean pub cache
      #   run: flutter pub cache clean -f

      #   #clean build
      # - name: Clean Build
      #   run: flutter clean

      

      # Get Pub dependencies
      - name: Get dependencies
        run: flutter pub get

      # build apk
      - name: Build Android Apk
        run: flutter build apk --flavor development -t ./lib/main_development.dart
      #- run: flutter build apk --debug

      #because we are using flavor and release mode the generate apk name is app-development-release.apk. else it would have been app-debug.apk
      - name: Rename build for Android
        # run: mv app-development-release.apk ${{ github.workspace }}/korbil_android.apk
        run: mv app-development-debug.apk ${{ github.workspace }}/korbil_android_debug.apk
        working-directory: build/app/outputs/flutter-apk

      - name: Draft release with release notes
        id: create_release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}
        with:
          tag_name: release
          name: Android Apk
          prerelease: false
          generate_release_notes: false
          files: |
            korbil_android_debug.apk
