name: Builds
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  draft-release:
    name: Build android
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false 
    steps:
      - uses: actions/checkout@v4
    
      # Set up Flutter.
      - name: Setup flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.5'
          channel: 'stable'
          cache: true
      - run: flutter doctor -v

      # Install Android dependency
      - name: Set up JDK 
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: zulu
          cache: gradle

      # Get Pub dependencies
      - run: |
          flutter pub cache clean -f
          flutter clean
          rm ./pubspec.lock
          flutter pub get
          flutter build apk --flavor development -t ./lib/main_development.dart
      #- run: flutter build apk --debug

      
      - name: Rename build for Android
        run: mv app-debug.apk ${{ github.workspace }}/korbil_android.apk
        working-directory: build/app/outputs/flutter-apk

      - name: Draft release with release notes
        id: create_release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}
        with:
          tag_name: release
          name: Android Apk
          prerelease: false
          generate_release_notes: false
          files: |
            korbil_android.apk
